from typing import Any, Protocol


class MessageBus(Protocol):
    def receive(self, max_messages: int = 1, wait_time_seconds=5, delete_after_polling=True) -> list[Any]: ...
    def send(self, message: Any) -> None: ...


class S3Compatible(Protocol):
    def store(self, key: str, data: Any, bucket: str) -> None: ...
    def retrieve(self, key: str, bucket: str) -> Any: ...


class ModelRunner(Protocol):
    def predict(self, batch: list[Any]) -> list[Any]: ...
